FROM python:3-alpine
MAINTAINER Jean-Marc Astesana <admin@fathzer.com>

WORKDIR ./lichessbot

COPY . .

RUN python3 -m pip install --no-cache-dir -r requirements.txt

ENV LICHESS_BOT_DOCKER="true"

CMD python3 lichess-bot.py ${OPTIONS} --disable_auto_logging --config /engine/config.yml
