name: Docker CI

on:
  # Configure Manual Trigger
  workflow_dispatch:
    inputs:
      dockerTagPrefix:
        description: 'Docker image tag prefix'
        required: true
        default: 'latest'
  push:
    branches:
      - master
      - github-repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Assign defaultValue
        run: |
          USER_INPUT="${{ github.event.inputs.dockerTagPrefix }}"
          # Use user input or fall back to "latest"
          dockerTag=${USER_INPUT:-"latest"}
          echo dockerTag="$dockerTag" >> "$GITHUB_ENV"
          # Use $dockerTag-alpine or fall back to "alpine"
          dockerAlpineTag=$([ "$dockerTag" = "latest" ] && echo "alpine" || echo $dockerTag"-alpine")
          echo dockerAlpineTag="$dockerAlpineTag" >> "$GITHUB_ENV"
      
      - name: show me docker tags.
        run: |
          echo "dockerTag:'"$dockerTag"'"
          echo "dockerAlpineTag:'"$dockerAlpineTag"'"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
          
#      - name: Login to container registry
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.GITHUB_USER }}
#          password: ${{ secrets.GITHUB_PWD }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app
          
      - name: Demo build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: build and push fat image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_IMG }}:${{env.dockerTag}}          

      - name: build and push alpine image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: VARIANT=-alpine
          push: true
          tags: ${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_IMG }}:${{env.dockerAlpineTag}}